---
title: Australia Inflation Trends
author: Christian Klettner
date: today
date-format: DD MMM YYYY
execute: 
  echo: false
  warning: false
  message: false
---

The latest Australian inflation trends by category.

```{r}
library(tidyverse)
library(tsibble)
library(gt)
```

```{r}
source("mcpi.R")
```

```{r}
#| tbl-cap: "Year on year change in monthly CPI by expenditure category" 
mcpi %>% 
  filter(time_period %in% c(max(time_period) + c(0, -12))) %>% 
  as_tibble() %>% 
  pivot_wider(id_cols=category, names_from = time_period, values_from=price.4q) %>% 
  gt(rowname_col="category") %>%  
  fmt_percent(columns=c(2,3)) 
```


```{r}
#| fig-cap: "CPI by Category" 
#| fig-alt: "CPI by Category"
#| fig-height: 10
#| fig-width: 8
mcpi %>%  
  filter(category!="All groups CPI") %>% 
  ggplot(aes(x=time_period, y=price.4q)) + 
  annotate("rect", xmin=-Inf, xmax=Inf, 
           ymin=0.02, ymax=0.03, fill="lightgrey") +
  geom_line(aes(color=category, linetype="Monthly CPI")) + 
  geom_text(
    data=~filter(.x, time_period==max(time_period)) %>% 
      mutate(label= scales::label_percent(accuracy=0.1)(price.4q)), 
    aes(color=category, label=label), 
    hjust="left", size=3) + 
  geom_line(
    mapping=aes(color=category, linetype="Quarterly CPI"), 
    data =filter(qcpi, 
      category!="All groups CPI" & time_period >= yearquarter("2015-Q3"))) +
  facet_wrap(vars(category), 
             labeller = labeller(category= \(x) str_wrap(x, width=20))) + 
  geom_line(data=mcpi %>% filter(category=="All groups CPI") %>% 
              rename(all=category), 
            aes(x=time_period, y=price.4q, linetype="All Groups")) +
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  scale_x_yearmonth(date_labels = "%y", 
                    expand=expansion(add = c(0, 500))) + 
  scale_linetype_manual(values=c("solid", "solid", "dashed")) +
  theme_bw() + 
  theme(strip.background = element_blank(), 
        legend.position = c(1,0), 
        legend.justification = c(1,0)) + 
  guides(color="none") + 
  labs(subtitle=paste("As at:", as.character(max(mcpi$time_period))),
       y="Year on Year Change",
       x=NULL, linetype=NULL)
```

